include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "**/*.g.dart"

formatter:
  trailing_commas: preserve
  page_width: 80

linter:
  rules:
    prefer_relative_imports: true
    avoid_empty_else: true
    avoid_print: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    unnecessary_library_name: false
    close_sinks: true
    control_flow_in_finally: true
    discarded_futures: true
    empty_statements: true
    hash_and_equals: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_void_to_null: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    unsafe_html: true
    use_key_in_widget_constructors: true
    valid_regexps: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_annotating_with_dynamic: false
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    avoid_classes_with_only_static_members: true
    avoid_escaping_inner_quotes: false
    avoid_field_initializers_in_const_classes: true
    avoid_final_parameters: true
    avoid_function_literals_in_foreach_calls: true
    avoid_init_to_null: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: false
    avoid_return_types_on_setters: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    prefer_single_quotes: true
    use_enums: true
    use_is_even_rather_than_modulo: true
    use_if_null_to_convert_nulls_to_bools: true
    use_rethrow_when_possible: false
    sized_box_shrink_expand: true
    prefer_is_not_operator: true
    prefer_final_locals: true
    empty_catches: true
    use_super_parameters: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_new: true
    unnecessary_lambdas: true
    unnecessary_getters_setters: true
    unnecessary_const: true
    secure_pubspec_urls: true
    prefer_const_constructors: true
